[build]
publish = "demo/yun/dist"
command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm build && npx pnpm run build:demo"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/manifest.webmanifest"

[headers.values]
Content-Type = "application/manifest+json"
