packages:
  - api
  - docs
  - demo/*
  - demo/custom/valaxy-theme-custom
  - packages/*
  - packages/@valaxyjs/*
  - scripts
catalog:
  '@iconify-json/ant-design': ^1.2.5
  '@iconify-json/carbon': ^1.2.7
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/ri': ^1.2.5
  '@iconify-json/simple-icons': ^1.2.26
  '@iconify-json/vscode-icons': ^1.2.16
  typescript: ^5.7.3
  unbuild: ^3.3.1
  vite: ^6.1.1
  vue-i18n: ^11.1.1
  zx: ^8.3.2
